name: Build and run (Ubuntu)

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  workflow_dispatch:

jobs:
  docker-run:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - run: sudo apt-get install musl-tools
      - run: pip install uv
      - run: uv python install cpython-3.11.15-linux-x86_64-musl
      - run: python3.11 -m pip install pydantic==2.12.5
      - run: python3.11 app/main.py
