name: Build and run

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  workflow_dispatch:

jobs:
  docker-run:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v6
      - run: docker build -t a .
      - run: docker run a
